#!/bin/bash
# ---- Current To ----
# Simple bash scripts to enhance cd, inspired by zoxide and navita.

# -- Check for ct configuration file and dir --
CTDIR="$HOME/.config/currento"
CTHIST="$CTDIR/history"
CTLDIR="$CTDIR/lastdir"
if [ ! -d "$CTDIR" ]; then
    mkdir -p $CTDIR &>/dev/null
    echo "" > $CTHIST &>/dev/null
    echo "" > $CTLDIR &>/dev/null
fi

# -- Link Start --
function currento() {
    # Basic
    CHOICE=$1
    CURDIR=$(pwd)
    PRVDIR=$(dirname $CURDIR)

    # Check history list
    checklists(){
        if [ -z "$CHOICE" ]; then
            cd $HOME
        elif [ "$CHOICE" = .. ]; then
            cd ..
        else
            cd $CHOICE &>/dev/null
            if [ $? -eq 0 ]; then
                if [[ "$CHOICE" != *"/"* ]]; then CHOICE="${CHOICE}/"; fi
                savelastdir
                FILENAME="${CURDIR}/${CHOICE}"
                CHECK=$(cat $CTHIST | awk '{print $2}' | grep -x $FILENAME)
                if [ ! "$CHECK" ]; then
                    savetohist
                else
                    increasenum
                fi
            else
                CHECK=$(cat $CTHIST | grep $CHOICE | sort -k1,1nr | awk 'NR==1 {print $2}')
                if [ "$CHECK" ]; then
                    cd $CHECK
                    savelastdir
                    increasenum
                fi
            fi
        fi
    }

    increasenum(){
        FULLNAME=$(cat $CTHIST | grep $CHECK | awk 'NR==1')
        NAME=$(cat $CTHIST | grep $CHECK | awk 'NR==1 {print $2}')
        NUMBER=$(cat $CTHIST | grep $CHECK | awk 'NR==1 {print $1}')
        NEWNUMBER=$(($NUMBER + 1))

        sed -i "s|${NUMBER}    ${NAME}|${NEWNUMBER}    ${NAME}|" $CTHIST
    }
    
    savetohist(){
        CHECKHISTORY=$(cat $CTHIST | awk '{print $2}' | grep -x "$CURDIR/${CHOICE}")
        if [[ ! "$CHECKHISTORY" ]]; then
                echo "1    ${CURDIR}/${CHOICE}" >> $CTHIST
        fi
    }

    savelastdir(){
        if [ $CURDIR != "$HOME" ]; then
            echo $CURDIR > $CTLDIR
        fi
    }

    lastdir(){
        LASTDIR=$(cat $CTLDIR)
        cd $LASTDIR
        if [ $? -eq 0 ]; then
            savelastdir
        fi
    }

    history(){
        LIST=$(cat "$CTHIST")
        echo "$LIST"
    }

    clearhist(){
        echo "" > $CTHIST
    }

    help(){
        cat <<EOF
usage: cd <operation> [...]
operations:
    cd <directory/path> cd into the directory and save to history
    cd {-l --lastdir}   cd into the last visited directory
    cd {-h --history}   show list of directory you've visited
    cd {--help}         show this page

    cd {--clearhistory} to clear the history, ofc.

you can also use 'cd -' to go back into the last directory
EOF
    }

    case $1 in
        --help) help ;;
        -[hH]|--history) history ;;
        --clearhist|--clearhistory|--clear-history) clearhist ;;
        -|-l|-ld|--lastdir|--lastdirectory) lastdir ;;
        *) checklists ;;
    esac
}
alias ct=currento
alias cd=currento
