#!/bin/bash

# ---- Current To ----
# Simple bash scripts to enhance cd, inspired by zoxide and navita.


# -- Check for ct configuration file and dir --
CTDIR="$HOME/.config/currento"
CTHIST="$CTDIR/history"
CTLDIR="$CTDIR/lastdir"
if [ ! -d "$CTDIR" ]; then
    mkdir -p $CTDIR &>/dev/null
    echo "" > $CTHIST &>/dev/null
    echo "" > $CTLDIR &>/dev/null
fi


# -- Link Start --
function currento() {
    # Basic
    CHOICE=$1
    CURDIR=$(pwd)
    PRVDIR=$(dirname $CURDIR)

    # Check history list
    checklists(){
        if [ -z "$CHOICE" ]; then
            cd $HOME
        elif [ "$CHOICE" = .. ]; then
            cd ..
        else
            cd $CHOICE &>/dev/null
            if [ $? -eq 0 ]; then
                savetohist
                savelastdir
            else
                CHECK=$(cat $CTHIST | grep $CHOICE | awk 'NR==1')
                if [ "$CHECK" ]; then
                    cd $CHECK
                    savelastdir
                else
                    cd $CHOICE
                    if [ $? -eq 0 ]; then
                        savetohist
                        savelastdir
                    fi
                fi
            fi
        fi
    }

    savelastdir(){
        if [ $CURDIR != "$HOME" ]; then
            echo $CURDIR > $CTLDIR
        fi
    }

    savetohist(){
        CHECKHISTORYLIST=$(cat $CTHIST | grep $CURDIR/$CHOICE)
        if [ ! "$CHECKHISTORYLIST" ]; then
            echo $CURDIR/$CHOICE >> $CTDIR/history
        fi
    }

    lastdir(){
        LASTDIR=$(cat $CTLDIR)
        cd $LASTDIR
        if [ $? -eq 0 ]; then
            savelastdir
        fi
    }

    history(){
        LIST=$(cat "$CTHIST")
        echo "$LIST"
    }

    help(){
        cat <<EOF
usage: cd <operation> [...]
operations:
    cd <directory/path> cd into the directory and save to history
    cd {-l --lastdir}   cd into the last visited directory
    cd {-h --history}   show list of directory you've visited
    cd {--help}         show this page

you can also use 'cd -' for cd to the last directory
EOF
    }

    case $1 in
        --help) help ;;
        -[hH]|--history) history ;;
        -|-l|-ld|--lastdir|--lastdirectory) lastdir ;;
        *) checklists ;;
    esac
}
alias ct=currento
alias cd=currento
